# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.openshift.tags= \
      io.k8s.description="My first Apache RHOCP app" \
      io.openshift.expose-services="8080:http"
EXPOSE 8080
